version: '3.8'

services:
  econutri-api:
    image: ghcr.io/abetlen/llama-cpp-python:latest
    container_name: econutri_api_container
    ports:
      - "8000:8000"
    volumes:
      - ./weights:/app/models
    restart: unless-stopped
    environment:
      - MODEL=/app/models/qwen2.5-3b-instruct-q4_k_m.gguf
      - HOST=0.0.0.0
      - PORT=8000
      - N_CTX=4096