version: '3.8'

services:
  llm-api:
    image: ghcr.io/abetlen/llama-cpp-python:latest
    container_name: llm_api_container
    ports:
      - "8000:8000"
    volumes:
      - ./weights:/app/models
    restart: unless-stopped
    environment:
      - MODEL=/app/models/qwen2.5-3b-instruct-q4_k_m.gguf
      - HOST=0.0.0.0
      - PORT=8000
      - N_CTX=4096
      - N_THREADS=4
      - N_THREADS_BATCH=4

  vision-api:
    build:
      context: .
      dockerfile: Dockerfile.vision
    container_name: vision_api_container
    ports:
      - "8001:8001"
    volumes:
      - ./weights:/app/weights
      - ./src:/app/src
      - ./configs:/app/configs
    restart: unless-stopped