FROM python:3.10-slim

# Cài đặt các thư viện lõi hệ thống cần cho OpenCV
RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements_vision.txt .
RUN pip install --no-cache-dir -r requirements_vision.txt

# Server sẽ khởi chạy bằng command truyền từ docker-compose
CMD ["uvicorn", "src.cloud_api_vision:app", "--host", "0.0.0.0", "--port", "8001"]